version: '3'

services:
  db:
    image: postgres:16.0
    container_name: proyecto_backend_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/wal:/wal
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./db/pgadmin-data:/var/lib/pgadmin
  node:
    build: .
    container_name: node_proyecto_backend
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules