INSERT INTO "user" (name, password, role)
VALUES
('admin', '$2a$10$//w7rNsMdlLSuy8r6yU7ueiahYqvab2hpP6JJHYnqRwVKMEqEiApS', 'admin'), ('victor', '$2a$10$gsQfsS93Iu6tqgrZ0K2vlO3CsZR.HJyRPGzwbMURcTuQ.2a185BkW
', 'user'), ('ander', '$2a$10$kMi27vUOPVEPz8EFAj5WwOcT.wfgUmgQBFBw.mBsUblTPydYAxM4q', 'user'), ('jon', '$2a$10$kMi27vUOPVEPz8EFAj5WwOcT.wfgUmgQBFBw.mBsUblTPydYAxM4q', 'user');


INSERT INTO "category" (name)
VALUES ('microondas'),('patinetes');

/* INSERT INTO "product" (title, description, picture, price, id_category)
VALUES
('Microondas Bosch', 'Calienta de locos', 'https://electromanchon.com/wp-content/uploads/2020/12/principal-188.jpg', 50, 1), ('Microondas Fagor', 'Caliente muy bien', 'https://www.outletelectrodomesticos.com/media/catalog/product/cache/1/image/650x/040ec09b1e35df139433887a97daa66f/f/o/foto_microondas_integrable_fagor_mwb-17aex_02.jpg', 40, 1), ('Micronodas Cecotec','Este es un mierda', 'https://static.carrefour.es/hd_510x_/crs/cdn_static/catalog/hd/285660_00_1.jpg', 20, 1), ('Patinete Xiaomi','vas volando','https://i01.appmifile.com/webfile/globalweb/chenyang/ess03.png', 150, 2), ('Patinete Cecotec','No tira ni patras' ,'https://img.pccomponentes.com/articles/17/178597/outsider-phoenix-cecotec-front.jpg', 100, 2), ('Microondas Orbegozo','Para calentar el tupper','https://m.media-amazon.com/images/I/61onzCymiFL.jpg',60, 1);
 */

INSERT INTO "product" (title, description, picture, price, id_category)
VALUES
('Xiaomi Mi Electric Scooter Pro 2 Patinete Eléctrico Negro', 'Destaca entre la multitud con este patinete eléctrico de edición limitada, que presenta un diseño exclusivo y elegante. Alcanza velocidades de hasta 30 km/h y es perfecto para quienes buscan un toque único en su movilidad urbana.', 'https://thumb.pccomponentes.com/w-300-300/articles/30/308149/1129-xiaomi-mi-electric-scooter-pro-2-patinete-electrico-negro.jpg', 499.98, 2),
('Cecotec Bongo Serie D30 XL Patinete Eléctrico 10" 350W Negro', 'Domina los senderos urbanos y suburbanos con este patinete eléctrico diseñado para enfrentar terrenos de montaña. Alcanza velocidades de 40 km/h y ofrece neumáticos resistentes para una experiencia todoterreno.', 'https://thumb.pccomponentes.com/w-300-300/articles/1078/10780233/1914-cecotec-bongo-serie-d30-xl-patinete-electrico-10-350w-negro.jpg', 657.79, 2),
('SmartGyro Rockway Certificado Patinete Eléctrico 10" 800W Negro', 'Experimenta el lujo en cada viaje con este patinete eléctrico que presenta elegantes acabados de cuero. Alcanza velocidades de 25 km/h y es ideal para aquellos que aprecian la comodidad y el estilo.', 'https://thumb.pccomponentes.com/w-300-300/articles/1078/10788315/1587-smartgyro-rockway-certificado-patinete-electrico-10-800w-negro.jpg', 276.99, 2),
('Xiaomi Mi Electric Scooter Essential Patinete Eléctrico Negro', 'Agrega un toque futurista a tus desplazamientos con este patinete eléctrico que cuenta con un sistema de iluminación ambiental personalizable. Alcanza velocidades de 32 km/h y garantiza una presencia llamativa en la noche.', 'https://thumb.pccomponentes.com/w-300-300/articles/30/308154/1604-xiaomi-mi-electric-scooter-essential-patinete-electrico-negro-foto.jpg', 500.90, 2),
('Cecotec Bongo Serie X65 Connected Patinete Eléctrico 10" 500W Verde', 'Diseñado con líneas aerodinámicas, este patinete eléctrico no solo es elegante, sino que también alcanza velocidades sorprendentes de 35 km/h. Experimenta la velocidad con estilo en cada recorrido.', 'https://thumb.pccomponentes.com/w-300-300/articles/1078/10780239/1582-cecotec-bongo-serie-x65-connected-patinete-electrico-10-500w-verde.jpg', 386.99, 2),
('Navee V40 Pro Patinete Eléctrico 10" Negro', 'Adaptable a todas las edades, este patinete eléctrico presenta un manillar ajustable que lo hace perfecto tanto para niños como para adultos. Alcanza velocidades de 20 km/h y es una opción versátil para toda la familia.', 'https://thumb.pccomponentes.com/w-300-300/articles/1079/10790228/1224-navee-v40-pro-patinete-electrico-10-negro.jpg', 499.98, 2),
('Xiaomi Mi Electric Scooter 3 Lite Patinete Eléctrico', 'Experimenta la emoción de las carreras con este patinete eléctrico que ofrece un modo deportivo para velocidades máximas. Alcanza los 45 km/h y brinda una experiencia de conducción emocionante para los entusiastas de la velocidad.', 'https://thumb.pccomponentes.com/w-300-300/articles/1056/10568375/1265-xiaomi-mi-electric-scooter-3-lite-patinete-electrico-negro.jpg', 899.85, 2),
('Acer Electrical Scooter 5 Patinete Eléctrico 10" 350W Negro', 'Mantén tus dispositivos cargados sobre la marcha con este patinete eléctrico que incorpora un sistema de carga inalámbrica. Alcanza velocidades de 28 km/h y ofrece una solución conveniente para mantener tus dispositivos energizados.', 'https://thumb.pccomponentes.com/w-300-300/articles/1077/10773720/1725-acer-electrical-scooter-5-patinete-electrico-10-350w-negro.jpg', 749.00, 2),
('Xiaomi Mi Electric Scooter 4 Patinete Eléctrico 25Km/h Negro', 'Experimenta la libertad en movimiento con nuestro patinete plegable, pesando solo 8 kg y alcanzando velocidades de hasta 25 km/h, perfecto para desplazamientos urbanos eficientes.', 'https://thumb.pccomponentes.com/w-300-300/articles/1073/10733114/1373-xiaomi-mi-electric-scooter-4-patinete-electrico-25km-h-negro.jpg', 385.99, 2),
('UrbanGlide Ecross Pro Boost Patinete Eléctrico', 'Con ruedas todoterreno resistentes y una potente batería, este patinete eléctrico alcanza los 35 km/h y es ideal para aventuras urbanas y suburbanas. Disfruta de una autonomía de hasta 40 km.', 'https://thumb.pccomponentes.com/w-300-300/articles/1037/10370330/1785-urbanglide-ecross-pro-boost-patinete-electrico.jpg', 319.00, 2),
('Xiaomi Electric Scooter 4 Ultra Patinete Eléctrico 25km/h 500W Negro', 'Diseñado con elegancia y comodidad en mente, nuestro patinete eléctrico combina estilo urbano con una conducción suave. Alcanza velocidades de 20 km/h y cuenta con una batería de larga duración.', 'https://thumb.pccomponentes.com/w-300-300/articles/1072/10728935/1829-xiaomi-electric-scooter-4-ultra-patinete-electrico-25km-h-500w-negro.jpg', 455.99, 2),
('SmartGyro Rockway Pro C Patinete Eléctrico Negro', 'Pensado para los más jóvenes aventureros, este patinete eléctrico infantil alcanza velocidades seguras de hasta 15 km/h y garantiza una experiencia divertida y segura en cada viaje.', 'https://thumb.pccomponentes.com/w-300-300/articles/1078/10788316/1880-smartgyro-rockway-pro-c-patinete-electrico-negro.jpg', 599.00, 2),
('B-Mov FreeStyle 5 2023 Patinete Eléctrico 10" 800W', 'Compacto pero potente, este patinete eléctrico alcanza los 30 km/h y ofrece una autonomía impresionante de 45 km. Ideal para desplazamientos diarios en la ciudad sin preocuparte por recargar constantemente.', 'https://thumb.pccomponentes.com/w-300-300/articles/1074/10744438/1461-b-mov-freestyle-5-2023-patinete-electrico-10-800w-negro-rojo.jpg', 749.00, 2),
('SmartGyro Z-ONE Certificado Patinete Eléctrico 10" 350W', 'Este versátil patinete eléctrico no solo es perfecto para desplazamientos urbanos, sino que también cuenta con luces LED integradas para mayor seguridad nocturna y una aplicación para un control total desde tu smartphone.', 'https://thumb.pccomponentes.com/w-300-300/articles/1079/10791048/1618-smartgyro-z-one-certificado-patinete-electrico-10-350w-gris.jpg', 739.00, 2),
('Segway Ninebot KickScooter GT2 Patinete Eléctrico 11" 1500W', 'Con una velocidad máxima de 25 km/h y una capacidad de respuesta excepcional, este patinete eléctrico es la opción perfecta para aquellos que buscan una experiencia de conducción ágil y emocionante.', 'https://thumb.pccomponentes.com/w-300-300/articles/1065/10655943/1895-segway-ninebot-kickscooter-gt2-patinete-electrico-11-1500w.jpg', 929.00, 2),
('Xiaomi Mi Electric Scooter Patinete Eléctrico', 'Contribuye a un futuro sostenible con nuestro patinete eléctrico, impulsado por energía eléctrica limpia. Alcanza velocidades de 22 km/h y ofrece una alternativa ecológica para tu movilidad diaria.', 'https://thumb.pccomponentes.com/w-300-300/articles/15/156542/j1.jpg', 379.99, 2),
('SmartGyro Z-Pro Patinete Eléctrico 10" Negro', 'Diseñado para acompañarte en tus viajes, este patinete eléctrico plegable se pliega fácilmente para caber en el maletero de tu coche o en el compartimento de equipaje de un tren. Velocidad máxima de 20 km/h.', 'https://thumb.pccomponentes.com/w-300-300/articles/1076/10769565/1557-smartgyro-z-pro-patinete-electrico-10-negro.jpg', 279.95, 2),
('Cecotec Bongo Serie Z Power City Patinete Electrico 10.5" 800W', 'Experimenta la elegancia en movimiento con nuestro patinete eléctrico ejecutivo, que alcanza velocidades de 28 km/h y ofrece una autonomía de 35 km. Perfecto para profesionales que buscan una solución rápida y eficiente para sus desplazamientos urbanos.', 'https://thumb.pccomponentes.com/w-300-300/articles/1076/10763304/1311-cecotec-bongo-serie-z-power-city-patinete-electrico-105-800w.jpg', 649.00, 2),
('SmartGyro K2 Patinete Eléctrico 800W 25Km/h Titán', 'Para los amantes de la velocidad, este patinete eléctrico alcanza una emocionante velocidad máxima de 40 km/h, brindando una experiencia llena de adrenalina en cada viaje, respaldado por una autonomía de 30 km.', 'https://thumb.pccomponentes.com/w-300-300/articles/1073/10733106/1599-smartgyro-k2-patinete-electrico-80w-25km-h-titan.jpg', 1756.80, 2),
('Segway Ninebot KickScooter MAX G2E Patinete Eléctrico 10" 450W Negro', 'La combinación perfecta de ejercicio y comodidad, este patinete híbrido te permite pedalear o disfrutar de la asistencia eléctrica, brindando opciones versátiles para tus desplazamientos urbanos. Velocidad máxima de 25 km/h.', 'https://thumb.pccomponentes.com/w-300-300/articles/1071/10719584/192-segway-ninebot-kickscooter-max-g2e-patinete-electrico-10-450w-negro-opiniones.jpg', 499.98, 2),
('Segway Ninebot Kickscooter MAX G30E II Patinete Eléctrico', 'Supera los baches con facilidad gracias al sistema de suspensión de última generación de este patinete. Alcanza velocidades de 30 km/h y ofrece una conducción suave y cómoda en cualquier terreno.', 'https://thumb.pccomponentes.com/w-300-300/articles/1014/10140124/1463-segway-ninebot-kickscooter-max-g30e-ii-patinete-electrico.jpg', 291.99, 2),
('Olsson Fresh Advanced Patinete Eléctrico 10" Blanco', 'Haciendo una declaración de estilo, este patinete eléctrico no solo ofrece un rendimiento excepcional (35 km/h), sino que también cuenta con luces RGB personalizables para destacar en la noche y expresar tu personalidad.', 'https://thumb.pccomponentes.com/w-300-300/articles/1063/10633667/1361-olsson-fresh-advanced-patinete-electrico-10-blanco.jpg', 729.00, 2),
('UrbanGlide Ecross Pro Patinete Eléctrico 48v/800w/13ah', 'Experimenta la innovación con un sistema de frenado regenerativo que maximiza la eficiencia de la batería. Este patinete de gama alta alcanza los 32 km/h y es perfecto para aquellos que buscan lo último en tecnología.', 'https://thumb.pccomponentes.com/w-300-300/articles/1032/10328450/1711-urbanglide-ecross-pro-patinete-electrico-48v-800w-13ah.jpg', 578.57, 2),
('Segway P65E Patinete Eléctrico 10" Negro', 'Diseñado para conquistar cualquier terreno, este patinete todoterreno alcanza velocidades de 38 km/h y ofrece neumáticos resistentes para una travesía sin límites en la ciudad y más allá.', 'https://thumb.pccomponentes.com/w-300-300/articles/1064/10643452/1826-segway-p65e-patinete-electrico-10-negro-8e051186-2f99-4983-b2f0-e808925236e3.jpg', 988.87, 2),
('Olsson Unique Patinete Eléctrico 8', 'Disfruta de la comodidad de un asiento ajustable en tu patinete eléctrico. Con una velocidad máxima de 20 km/h, este modelo es perfecto para aquellos que prefieren una posición más relajada durante sus desplazamientos.', 'https://thumb.pccomponentes.com/w-300-300/articles/1050/10505410/1291-olsson-unique-patinete-electrico-8.jpg', 379.95, 2),
('Xiaomi Electric Scooter 4 Lite 300W 25Km/h Negro', 'Satisface las necesidades de toda la familia con este patinete eléctrico versátil, adecuado para niños y adultos. Alcanza velocidades seguras de 18 km/h y garantiza momentos divertidos para todas las edades.', 'https://thumb.pccomponentes.com/w-300-300/articles/1073/10733115/1580-xiaomi-electric-scooter-4-lite-300w-25km-h-negro.jpg', 899.85, 2),
('Segway Ninebot KickScooter C2 Pro Patinete Eléctrico 7" 150W', 'Navega por la ciudad con facilidad gracias al sistema de navegación GPS integrado en este patinete eléctrico. Con una velocidad máxima de 28 km/h, siempre llegarás a tu destino de manera eficiente.', 'https://thumb.pccomponentes.com/w-300-300/articles/1071/10719592/131-segway-ninebot-kickscooter-c2-pro-patinete-electrico-7-150w.jpg', 657.79, 2),
('Red Bull Racing Teen 10" Patinete Eléctrico 350W Negro/Rojo', 'Para aquellos que aprecian la elegancia simple, este patinete eléctrico de diseño minimalista ofrece una experiencia de conducción tranquila con una velocidad máxima de 22 km/h, perfecto para desplazamientos diarios sin complicaciones', 'https://thumb.pccomponentes.com/w-300-300/articles/1074/10749890/1804-red-bull-racing-teen-10-patinete-electrico-350w-negro-rojo.jpg', 276.99, 2),
('SmartGyro K2 Army Certificado Patinete Eléctrico 10" 800W Verde', 'Diseñado para la conveniencia, este patinete plegable se carga rápidamente y está listo para llevar en cuestión de horas. Alcanza velocidades de hasta 25 km/h y es ideal para quienes buscan movilidad sin esperas.', 'https://thumb.pccomponentes.com/w-300-300/articles/1078/10786308/1752-smartgyro-k2-army-certificado-patinete-electrico-10-800w-verde.jpg', 500.90, 2),
('Olsson Flip Patinete Eléctrico', 'Con un diseño compacto y peso ligero, este patinete eléctrico es perfecto para estudiantes que buscan una forma eficiente de moverse por el campus. Alcanza velocidades de 20 km/h y se pliega fácilmente para un almacenamiento conveniente.', 'https://thumb.pccomponentes.com/w-300-300/articles/31/312606/1503-olsson-flip-patinete-electrico.jpg', 386.99, 2),
('Segway KickScooter P100SE Patinete Eléctrico', 'Combina estilo vintage con tecnología moderna con este patinete eléctrico de diseño retro. Alcanza velocidades de 30 km/h y ofrece una forma elegante de explorar la ciudad con un toque clásico.', 'https://thumb.pccomponentes.com/w-300-300/articles/1070/10704791/1668-segway-kickscooter-p100se-patinete-electrico.jpg', 499.98, 2),
('NIU KQi2 Pro Patinete Eléctrico', 'Disfruta de un viaje constante con el control de crucero incorporado en este patinete eléctrico. Alcanza velocidades de hasta 28 km/h y permite una conducción relajada en trayectos más largos.', 'https://thumb.pccomponentes.com/w-300-300/articles/1021/10218939/1471-niu-kqi2-pro-patinete-electrico-blanco.jpg', 899.85, 2),
('Segway Ninebot KickScooter E2 Plus Patinete Eléctrico', 'Experimenta la ligereza y resistencia con este patinete eléctrico fabricado en fibra de carbono. Alcanza velocidades de 30 km/h y ofrece una opción elegante y duradera para tus desplazamientos diarios.', 'https://thumb.pccomponentes.com/w-530-530/articles/1074/10742728/1285-segway-ninebot-kickscooter-e2-plus-patinete-electrico-foto.jpg', 749.00, 2),
('Youin XL Max Lite Patinete Eléctrico 800W Negro', 'Lleva tu música contigo mientras te desplazas con este patinete eléctrico que cuenta con un sistema de sonido integrado. Alcanza velocidades de 25 km/h y añade un toque musical a tus paseos urbanos.', 'https://thumb.pccomponentes.com/w-300-300/articles/1072/10722822/1268-youin-xl-max-lite-patinete-electrico-800w-negro.jpg', '385.99', 2),
('Xiaomi Electric Scooter 4 Pro Patinete Eléctrico Negro', 'Diseñado con las últimas características tecnológicas, este patinete eléctrico se conecta a tu dispositivo móvil para un control total. Alcanza velocidades de 30 km/h y es perfecto para aquellos que aman la innovación.', 'https://thumb.pccomponentes.com/w-300-300/articles/1056/10568412/1252-xiaomi-electric-scooter-4-pro-patinete-electrico-negro.jpg', 319.00, 2),
('Xiaomi Mi Electric Scooter 3', 'Expresa tu personalidad eligiendo entre una variedad de colores personalizables para este patinete eléctrico. Con una velocidad máxima de 22 km/h, combina estilo y rendimiento a tu manera.', 'https://thumb.pccomponentes.com/w-300-300/articles/51/514037/1878-xiaomi-mi-electric-scooter-3-negro.jpg', 455.99, 2),
('SmartGyro Xtreme SpeedWay Patinete Eléctrico Negro/Azul', 'Ideal para distancias cortas en la ciudad, este patinete eléctrico ligero alcanza velocidades de hasta 18 km/h y facilita la movilidad rápida y eficiente en entornos urbanos congestionados.', 'https://thumb.pccomponentes.com/w-300-300/articles/24/241335/a19.jpg', 599.00, 2),
('Xiaomi Electric Scooter 4 Go Patinete Eléctrico Negro/Naranja', 'Priorizando la seguridad, este patinete eléctrico cuenta con un sistema de frenado antibloqueo que garantiza una parada suave y controlada. Alcanza velocidades de 26 km/h y es perfecto para aquellos que valoran la seguridad en su viaje.', 'https://thumb.pccomponentes.com/w-300-300/articles/1074/10749641/1111-xiaomi-electric-scooter-4-go-patinete-electrico-negro-naranja.jpg', 749.00, 2),
('SkateFlash Echo Patinete Eléctrico Negro', 'Ofreciendo un equilibrio entre rendimiento y autonomía, este patinete eléctrico de gama media alcanza velocidades de 28 km/h y brinda una autonomía mejorada de 40 km, ideal para usuarios que buscan duración en sus viajes.', 'https://thumb.pccomponentes.com/w-300-300/articles/62/621007/1967-skateflash-echo-patinete-electrico-negro.jpg', 739.00, 2),
('Cecotec Bongo M40 Connected Patinete Eléctrico 700W', 'Diseñado específicamente para jóvenes aventureros, este patinete todoterreno alcanza velocidades emocionantes de 35 km/h y ofrece la resistencia necesaria para explorar terrenos variados con confianza.', 'https://thumb.pccomponentes.com/w-300-300/articles/1076/10763310/1693-cecotec-bongo-m40-connected-patinete-electrico-700w.jpg', 929.00, 2);



INSERT INTO "product" (title, description, picture, price, id_category) VALUES
	('Origial ORIMICG20FSS Infinityheat Microondas con Grill 20L 1000W Silver', 'Este microondas compacto es la solución perfecta para espacios pequeños. Con una potencia de 700W, ofrece funciones de descongelado y mantener calor, asegurando eficiencia a un precio asequible. Su diseño elegante y tamaño conveniente lo convierten en una adición práctica para cualquier cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/1046/10465475/1957-origial-orimicg20fss-infinityheat-microondas-con-grill-20l-1000w-silver.jpg', 51.90, 1),
	('Cecotec ProClean 3010 Microondas 20L 700W', 'Experimenta la versatilidad culinaria con nuestro microondas de 900W y grill integrado. Ideal para dorar y gratinar, este electrodoméstico combina potencia y funcionalidad, ofreciendo resultados deliciosos. Su diseño moderno y compacto lo convierte en un complemento atractivo para tu cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/175683/1375-cecotec-proclean-3010-microondas-20l-700w-especificaciones.jpg', 49.90, 1),
	('Cecotec ProClean 2010 Microondas 20L 700W', 'Simplifica tu cocina con nuestro microondas digital de 800W, equipado con una pantalla LED fácil de usar. Ajusta con precisión el tiempo y la potencia para obtener resultados perfectos. Su diseño elegante y funcionalidad hacen que cocinar sea más eficiente y placentero.', 'https://thumb.pccomponentes.com/w-300-300/articles/23/239505/01587-proclean-2010-hq.jpg', 55.65, 1),
	('Orbegozo MI 2115 Microondas 20L 700W Blanco', 'Descubre la potencia uniforme con nuestro microondas de 1000W y tecnología inverter. Garantiza un calentamiento uniforme para resultados perfectos. Su diseño moderno y eficiencia energética lo convierten en una elección inteligente para cualquier cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/26/266474/orbegozo-mi-2115-microondas-20l-700w-blanco-review.jpg', 68, 1),
	('Origial ORIMICG20FSMIR Infinityheat Microondas con Grill 20L 1000W Negro', 'Simplifica tu rutina culinaria con nuestro microondas equipado con sensores de cocina automática. Ajusta automáticamente el tiempo y la potencia según el plato, brindando comodidad sin esfuerzo. Este electrodoméstico de alta tecnología hace que cocinar sea más fácil que nunca.', 'https://thumb.pccomponentes.com/w-300-300/articles/43/433714/1345-origial-orimicg20fsmir-infinityheat-microondas-con-grill-20l-1000w-negro.jpg', 74.40, 1),
	('Teka MWE 225 FI Microondas con Grill Integrable 800W Acero Inoxidable', 'Eleva el estilo de tu cocina con nuestro microondas empotrable de 1200W y elegante acabado en acero inoxidable. Potencia y diseño se unen para crear una pieza central funcional y atractiva. Un complemento perfecto para cocinas modernas y sofisticadas.', 'https://thumb.pccomponentes.com/w-300-300/articles/15/150698/1896-teka-mwe-225-fi-microondas-con-grill-integrable-800w-acero-inoxidable-comprar.jpg', 229, '1'),
	('Orbegozo MI 2020 Microondas 20L 700W Rojo', 'Experimenta la versatilidad culinaria con nuestro microondas de 1100W con función de convección. Calienta, cocina y hornea con un solo electrodoméstico, ofreciendo comidas deliciosas con facilidad. Su diseño elegante y funciones avanzadas lo hacen imprescindible en cualquier cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/21/212560/1563-orbegozo-mi-2020-microondas-20l-700w-rojo-comprar.jpg', 59.90, 1),
	('Origial ORIMICNG20FSMIR Infinityheat Microondas 20L 700W Negro', 'Añade un toque de nostalgia a tu cocina con nuestro microondas de diseño retro. Con 800W de potencia, este electrodoméstico no solo es funcional sino también elegante. Un complemento llamativo que combina estilo y rendimiento.', 'https://thumb.pccomponentes.com/w-300-300/articles/43/433717/1881-origial-orimicng20fsmir-infinityheat-microondas-20l-700w-negro-comprar.jpg', 57.90, 1),
	('Samsung GE83X/XEC Microondas con Grill 23L 800W/Grill 1200W Espejo Negro', 'Simplifica tu vida ocupada con nuestro microondas programable. Con menús predefinidos, este electrodoméstico facilita la preparación de comidas. Personaliza tu experiencia culinaria con opciones avanzadas en un diseño moderno y compacto.', 'https://thumb.pccomponentes.com/w-300-300/articles/1074/10749460/1715-samsung-ge83x-xec-microondas-con-grill-23l-800w-grill-1200w-plata.jpg', 109, 1),
	('Cecotec ProClean 3030 Microondas 20L 700W Negro', 'Disfruta de comidas calientes mientras viajas con nuestro microondas portátil de 600W. Compacto y ligero, se conecta fácilmente a la toma del automóvil, brindándote la comodidad de cocinar dondequiera que vayas. Una solución perfecta para aquellos que buscan versatilidad sobre la marcha.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/177638/d1.jpg', 65.90, 1),
	('Balay 3CG5172N2 Microondas Integrable con Grill 20L 800W Cristal Negro', 'Experimenta la revolución culinaria con nuestro microondas de alta potencia y tecnología inteligente. Ajusta automáticamente los niveles de potencia y tiempo, garantizando resultados perfectos. Su diseño moderno y pantalla táctil hacen que cocinar sea más intuitivo que nunca.', 'https://thumb.pccomponentes.com/w-300-300/articles/1029/10298972/1333-balay-3cg5172n2-microondas-integrable-con-grill-20l-800w-cristal-negro.jpg', 275, 1),
	('Cecotec ProClean 3130 Microondas con Grill 20L 700W Negro', 'Dale un giro saludable a tus comidas con nuestro microondas con función de vapor. Con 900W de potencia, este electrodoméstico no solo calienta, sino que también conserva la textura y nutrientes de tus platillos. Una opción perfecta para aquellos que buscan opciones de cocina más saludables.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/177648/e1.jpg', 71.99, 1),
	('Bosch BFL520MS0 Serie 4 Microondas Integrable 20L 800W Acero Inoxidable', 'Disfruta de la tranquilidad en la cocina con nuestro microondas silencioso y eficiente energéticamente. Con 800W, este electrodoméstico de bajo consumo ofrece un rendimiento excepcional sin sacrificar la paz en tu hogar.', 'https://thumb.pccomponentes.com/w-300-300/articles/26/266480/bosch-bfl520ms0-serie-4-microondas-integrable-20l-800w-acero-inoxidable-caracteristicas.jpg', 107, 1),
	('Origial ORIMICG20FSMIRW Infinityheat Microondas con Grill 20L 1000W Blanco', 'Experimenta una cocción más uniforme con nuestro microondas de avanzada tecnología de ondas tridimensionales. Con 1000W, este electrodoméstico garantiza resultados consistentes en cada uso. Su diseño futurista y funciones avanzadas lo hacen destacar en cualquier cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/1046/10465478/1946-origial-orimicg20fsmirw-infinityheat-microondas-con-grill-20l-1000w-blanco.jpg', 314.72, 1),
	('Cecotec ProClean 3110 Microondas con Grill 20L 700W', 'Ilumina tu cocina con nuestro microondas equipado con iluminación LED interior. Con 1100W de potencia, este electrodoméstico no solo facilita la visibilidad, sino que también ofrece un rendimiento excepcional para tus necesidades culinarias diarias.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/177625/a1.jpg', 54.90, 1),
	('Balay 3CG6142X3 Microondas Integrable con Grill 20L 800W Inox', 'Prioriza la higiene en tu cocina con nuestro microondas innovador que utiliza tecnología de desinfección UV. No solo calienta tus alimentos con eficiencia (800W), sino que también garantiza un ambiente limpio y seguro para tus comidas.', 'https://thumb.pccomponentes.com/w-300-300/articles/1038/10385499/1978-balay-3cg6142x3-microondas-integrable-con-grill-20l-800w-inox.jpg', 54.90, 1),
	('Teka MW 225G Microondas con Grill 700W Blanco', 'Personaliza tu experiencia culinaria con nuestro microondas programable. Guarda tus ajustes favoritos para un acceso rápido, ofreciendo comodidad personalizada en cada uso. Con 950W, este electrodoméstico es la combinación perfecta de versatilidad y eficiencia.', 'https://thumb.pccomponentes.com/w-300-300/articles/12/129351/1385-teka-mw-225g-microondas-con-grill-700w-blanco-comprar.jpg', 185, 1),
	('Balay 3WG3112B0 Microondas con Grill 20L 800W Blanco', 'Mantén tu microondas impecable con nuestra versión de superficie antihuellas. Con 850W de potencia, este electrodoméstico no solo es fácil de limpiar, sino que también ofrece un rendimiento confiable y duradero para tu cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/1032/10329670/1723-balay-3wg3112b0-microondas-con-grill-20l-800w-blanco-comprar.jpg', 179.95, 1),
	('Teka MW 225 Microondas 700W Blanco', 'Olvídate de la limpieza con nuestro microondas equipado con un sistema de autolimpieza. Con 950W, este electrodoméstico no solo cocina con eficiencia, sino que también se encarga de mantenerse impecable después de cada uso.', 'https://thumb.pccomponentes.com/w-300-300/articles/12/128837/f11.jpg', 72.90, 1),
	('Cecotec ProClean 5010 Inox Microondas 700W', 'Contribuye al medio ambiente con nuestro microondas eco-friendly. Con un diseño eficiente energéticamente y materiales sostenibles, este electrodoméstico de 900W es una elección consciente para aquellos que buscan reducir su huella ecológica en la cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/174358/01534-proclean-5010-inox-1.jpg', 228, 1),
	('Origial ORIMICNG20FSW Infinityheat Microondas 20L 700W Blanco', 'Eleva tu experiencia culinaria con nuestro microondas de pantalla táctil a color. Con 1200W, este electrodoméstico no solo facilita la navegación, sino que también ofrece un rendimiento potente para tus recetas favoritas. Un toque de modernidad en tu cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/43/433712/1247-origial-orimicng20fsw-infinityheat-microondas-20l-700w-blanco.jpg', 159.95, 1),
	('Teka MS 620 BIH Microondas Integrable 20L 1100W Acero Inoxidable', 'Descubre la versatilidad con nuestro microondas multifunción de 1100W. Además de calentar, este electrodoméstico ofrece funciones de convección y grill, brindando opciones culinarias ilimitadas. Su diseño elegante y funciones avanzadas lo hacen esencial para los amantes de la cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/26/260836/teka-ms-620-bih-microondas-integrable-20l-1100w-acero-inoxidable.jpg', 259, 1),
	('Bosch BEL523MS0 Microondas Integrable con Grill 20L 800W Acero Inoxidable', 'Conéctate a la era digital con nuestro microondas inteligente con Wi-Fi. Controla y programa tu cocina desde tu dispositivo móvil, incluso cuando no estás en casa. Con 1000W, es la combinación perfecta de tecnología y comodidad.', 'https://thumb.pccomponentes.com/w-300-300/articles/26/268701/bosch-bel523ms0-microondas-integrable-con-grill-20l-800w-acero-inoxidable-caracteristicas.jpg', 249, 1),
	('Siemens BF520LMR0 Microondas Integrable 20L 800W Acero Inoxidable', 'Añade un toque de elegancia con nuestro microondas de diseño minimalista. Con 850W, este electrodoméstico combina funcionalidad y estética en una presentación moderna que se integra perfectamente en cualquier cocina contemporánea.', 'https://thumb.pccomponentes.com/w-300-300/articles/26/268699/siemens-bf520lmr0-microondas-integrable-20l-800w-acero-inoxidable-caracteristicas.jpg', 119, 1),
	('Origial ORIMICG20FSW InfinityHeat Microondas con Grill 20L 1000W Blanco', 'Cocina con precisión con nuestro microondas equipado con tecnología de sensor de humedad. Ajusta automáticamente el tiempo y la potencia para mantener la textura de tus alimentos. Con 950W, este electrodoméstico es perfecto para chefs exigentes.', 'https://thumb.pccomponentes.com/w-300-300/articles/43/433709/1611-origial-orimicg20fsw-infinityheat-microondas-con-grill-20l-1000w-blanco.jpg', 59.90, 1),
	('Samsung MG23J5133AK Horno Microondas con Grill 23L 800W Negro', 'Ilumina tu cocina y tus comidas con nuestro microondas de encimera con iluminación halógena. Con 900W de potencia, este electrodoméstico no solo ofrece un rendimiento excepcional, sino que también crea un ambiente acogedor en tu espacio culinario.', 'https://thumb.pccomponentes.com/w-300-300/articles/21/210592/1193-samsung-mg23j5133ak-horno-microondas-con-grill-23l-800w-negro-mejor-precio.jpg', 139.95, 1),
	('Balay 3CG5175N0 Microondas Integrable con Grill 25L 900W Cristal Negro', 'Descubre el sabor del asado con nuestro microondas de 1000W y función de aire caliente. Disfruta de platos dorados y crujientes sin necesidad de horno. Su diseño moderno y funciones avanzadas lo convierten en una opción imprescindible para cualquier cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/31/311162/137-balay-3cg5175n0-microondas-integrable-con-grill-25l-900w-cristal-negro.jpg', 51.90, 1),
	('Cecotec ProClean 2110 Microondas con Grill 20L 700W', 'Satisface las necesidades de tu familia con nuestro microondas de alta capacidad. Con 1200W, este electrodoméstico no solo es espacioso, sino que también ofrece un rendimiento potente para cocinar grandes cantidades de alimentos. Ideal para reuniones familiares y cenas festivas.', 'https://thumb.pccomponentes.com/w-300-300/articles/29/298223/cecotec-proclean-2110-microondas-20l-700w-foto.jpg', 49.90, 1),
	('Cecotec ProClean 3020 Microondas 20L 700W Blanco', 'Añade un toque de elegancia con nuestro microondas compacto y espejo reflectante. Con 800W, este electrodoméstico no solo ahorra espacio, sino que también agrega un toque moderno a tu cocina. Una opción ideal para espacios reducidos con estilo.', 'https://thumb.pccomponentes.com/w-300-300/articles/17/177631/b1.jpg', 55.65, 1),
	('Teka MWE 202 FI Microondas Integrable 20 Litros con Grill Acero Inoxidable', 'Disfruta de comidas frescas sin olores persistentes con nuestro microondas con función de desodorización. Con 950W, este electrodoméstico no solo cocina eficientemente, sino que también se encarga de mantener un ambiente fresco y agradable en tu cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/31/314086/1835-teka-mwe-202-fi-microondas-integrable-20-litros-con-grill-acero-inoxidable.jpg', 68, 1),
	('Cecotec Grandheat 2550 Built-in Steel Microondas Integrable con Grill 25L 1320W', 'Experimenta la elegancia y facilidad de uso con nuestro microondas con panel de control retroiluminado. Con 1100W, este electrodoméstico no solo ilumina tu cocina, sino que también ofrece un control intuitivo para tus necesidades culinarias diarias.', 'https://thumb.pccomponentes.com/w-300-300/articles/1067/10672042/18-cecotec-grandheat-2550-built-in-steel-microondas-integrable-con-grill-25l-1320w.jpg', 74.40, 1),
	('Cecotec ProClean 5120 Mirror Microondas con Grill 20L 700W', 'Agrega un toque de durabilidad a tu cocina con nuestro microondas compacto de acero inoxidable. Con 850W de potencia, este electrodoméstico no solo es resistente, sino que también ofrece un rendimiento fiable para tus comidas diarias.', 'https://thumb.pccomponentes.com/w-300-300/articles/18/185816/1537-cecotec-proclean-5120-mirror-microondas-con-grill-20l-700w-comprar.jpg', 229, 1),
	('Teka MWE 255 FI Microondas con Grill Integrable 900W Acero Inoxidable', 'Simplifica la limpieza con nuestro microondas de encimera con parrilla desmontable. Con 900W, este electrodoméstico no solo cocina con eficiencia, sino que también facilita la limpieza después de cada uso.', 'https://thumb.pccomponentes.com/w-300-300/articles/15/150715/40581125-mwe-255-fi.jpg', 59.90, 1),
	('Cecotec GrandHeat 2090 Built-In Steel Microondas Integrable 20L 800W Acero Inoxidable', 'Olvídate de las complicaciones al descongelar con nuestro microondas con programas de descongelación automática. Con 950W, este electrodoméstico garantiza un descongelamiento uniforme sin esfuerzo adicional. Ideal para aquellos que buscan comodidad en la cocina.', 'https://thumb.pccomponentes.com/w-300-300/articles/40/404761/1442-cecotec-grandheat-2090-built-in-steel-microondas-integrable-20l-800w-acero-inoxidable.jpg', 57.90, 1),
	('LG MJ3965BPS Microondas con Grill 1100W Negro', 'Experimenta la eficiencia de cocción con nuestro microondas de tecnología de infrarrojos. Con 1000W, este electrodoméstico garantiza resultados rápidos y uniformes, ahorrando tiempo en la preparación de tus comidas diarias.', 'https://thumb.pccomponentes.com/w-300-300/articles/11/119872/1.jpg', 109, 1),
	('Teka MWE 209 FI Microondas Integrable con Grill 20 Litros 800W Acero Inoxidable', 'Explora nuevas posibilidades culinarias con nuestro microondas con función de fermentación. Con 800W, este electrodoméstico no solo calienta, sino que también es perfecto para preparar masa de pan y yogur casero. Una opción versátil para amantes de la cocina creativa.', 'https://thumb.pccomponentes.com/w-300-300/articles/1064/10642067/1641-teka-mwe-209-fi-microondas-integrable-con-grill-20-litros-800w-acero-inoxidable.jpg', 65.90, 1),
	('Balay 3CG5172B2 Microondas Integrable con Grill 20L 800W Cristal Blanco', 'Satisface tu apetito rápidamente con nuestro microondas de alta velocidad. Con 1200W, este electrodoméstico es perfecto para calentar comidas en minutos, ofreciendo conveniencia sin comprometer el sabor.', 'https://thumb.pccomponentes.com/w-300-300/articles/1029/10298957/1191-balay-3cg5172b2-microondas-integrable-con-grill-20l-800w-cristal-blanco.jpg', 275, 1),
	('Teka MWE 230 G Microondas con Grill 23L 1000W Inox', 'Optimiza el recalentamiento de tus platillos con nuestro microondas de tecnología de recalentamiento inteligente. Con 950W, este electrodoméstico ajusta automáticamente los tiempos y la potencia para mantener la frescura y textura original de tus alimentos.', 'https://thumb.pccomponentes.com/w-300-300/articles/25/259898/teka-mwe-230-g-microondas-con-grill-23l-1000w-inox.jpg', 71.99, 1),
	('Cecotec Grandheat 3120 Microondas con Grill 20L 1050W Blanco', 'Prioriza la seguridad en tu hogar con nuestro microondas con sistema de bloqueo para niños. Con 900W, este electrodoméstico no solo cocina eficientemente, sino que también proporciona tranquilidad para las familias con niños pequeños.', 'https://thumb.pccomponentes.com/w-300-300/articles/1067/10671023/1909-cecotec-grandheat-3120-microondas-con-grill-20l-1050w-blanco-opiniones.jpg', 107, 1),
	('Cecotec GrandHeat 2000 Built-in SteelBlack Microondas Encastrable con Grill 20L 700W Negro', 'Simplifica tu experiencia en la cocina con nuestro microondas de diseño ergonómico. Con 850W, este electrodoméstico no solo es fácil de usar, sino que también ofrece un rendimiento confiable para satisfacer tus necesidades culinarias diarias.', 'https://thumb.pccomponentes.com/w-300-300/articles/34/342942/1756-cecotec-grandheat-2000-microondas-encastrable-negro.jpg', 314.72, 1);



INSERT INTO "cart" (id_user)
VALUES
(1),(2),(3),(4);

INSERT INTO "cart_item" (quantity,id_cart,id_product)
VALUES
(1,2,1),(2,3,2),(1,2,4),(1,4,5),(1,3,3);
